# Generated by Django 4.2.1 on 2023-06-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisr', '0002_album_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='tieu_su',
            field=models.CharField(default='', max_length=100),
        ),
    ]
